export const appUninstallWebhook = {
  topic: 'APP_UNINSTALLED',
  domain: 'toastshopping.myshopify.com',
  payload: {
    id: 43857412254,
    name: 'toastshoppingg',
    email: 'moowee310@gmail.com',
    domain: 'toastshopping.myshopify.com',
    province: '',
    country: 'DE',
    address1: 'Eichenstieg 10',
    zip: '21244',
    city: 'Buchholz',
    source: null,
    phone: '04181/283856',
    latitude: 53.34143659999999,
    longitude: 9.857130900000001,
    primary_locale: 'de',
    address2: '',
    created_at: '2020-07-17T16:40:43+02:00',
    updated_at: '2020-10-08T15:58:18+02:00',
    country_code: 'DE',
    country_name: 'Germany',
    currency: 'EUR',
    customer_email: 'moowee310@gmail.com',
    timezone: '(GMT+01:00) Europe/Berlin',
    iana_timezone: 'Europe/Berlin',
    shop_owner: 'Mo We',
    money_format: '€{{amount_with_comma_separator}}',
    money_with_currency_format: '€{{amount_with_comma_separator}} EUR',
    weight_unit: 'kg',
    province_code: null,
    taxes_included: true,
    auto_configure_tax_inclusivity: null,
    tax_shipping: null,
    county_taxes: true,
    plan_display_name: 'Developer Preview',
    plan_name: 'partner_test',
    has_discounts: false,
    has_gift_cards: false,
    myshopify_domain: 'toastshopping.myshopify.com',
    google_apps_domain: null,
    google_apps_login_enabled: null,
    money_in_emails_format: '€{{amount_with_comma_separator}}',
    money_with_currency_in_emails_format: '€{{amount_with_comma_separator}} EUR',
    eligible_for_payments: true,
    requires_extra_payments_agreement: false,
    password_enabled: true,
    has_storefront: true,
    eligible_for_card_reader_giveaway: false,
    finances: true,
    primary_location_id: 50622890142,
    cookie_consent_level: 'implicit',
    visitor_tracking_consent_preference: 'allow_all',
    force_ssl: true,
    checkout_api_supported: true,
    multi_location_enabled: true,
    setup_required: false,
    pre_launch_enabled: false,
    enabled_presentment_currencies: ['EUR'],
  },
};

export const currentAppInstallation = {
  'data': {
    'currentAppInstallation': {
      'activeSubscriptions': [
        {
          'name': 'Super Duper Plan',
          'returnUrl': 'https://np-shopify.eu.ngrok.io/',
          'id': 'gid://shopify/AppSubscription/20504051870',
          'status': 'ACTIVE',
          'createdAt': '2020-12-21T19:15:34Z',
          'trialDays': 0,
          'test': true,
        },
      ],
    },
  },
  'extensions': {
    'cost': {
      'requestedQueryCost': 2,
      'actualQueryCost': 2,
      'throttleStatus': {'maximumAvailable': 1000, 'currentlyAvailable': 998, 'restoreRate': 50},
    },
  },
};

export const subscriptionWebhook = {
  'webhook': {
    'topic': 'APP_SUBSCRIPTIONS_UPDATE',
    'domain': 'toastshopping.myshopify.com',
    'payload': {
      'app_subscription': {
        'admin_graphql_api_id': 'gid://shopify/AppSubscription/20497694878',
        'name': 'Super Duper Plan',
        'status': 'ACTIVE',
        'admin_graphql_api_shop_id': 'gid://shopify/Shop/43857412254',
        'created_at': '2020-12-21T14:04:19+01:00',
        'updated_at': '2020-12-21T14:04:24+01:00',
      },
    },
  },
};

const orderWebhook = {
  'webhook': {
    'topic': 'ORDERS_UPDATED',
    'domain': 'toastshopping.myshopify.com',
    'payload': {
      'id': 2892549914782,
      'email': 'mowe310@gmail.com',
      'closed_at': '2020-12-11T12:05:42+01:00',
      'created_at': '2020-11-16T17:12:36+01:00',
      'updated_at': '2020-12-16T18:47:57+01:00',
      'number': 24,
      'note': 'test',
      'token': '7e77c7ab8e219e7a5737b0ea42c31976',
      'gateway': 'manual',
      'test': false,
      'total_price': '126.00',
      'subtotal_price': '126.00',
      'total_weight': 983,
      'total_tax': '17.38',
      'taxes_included': true,
      'currency': 'EUR',
      'financial_status': 'paid',
      'confirmed': true,
      'total_discounts': '0.00',
      'total_line_items_price': '126.00',
      'cart_token': null,
      'buyer_accepts_marketing': false,
      'name': '#1024',
      'referring_site': null,
      'landing_site': null,
      'cancelled_at': null,
      'cancel_reason': null,
      'total_price_usd': '149.25',
      'checkout_token': null,
      'reference': null,
      'user_id': 58730021022,
      'location_id': null,
      'source_identifier': null,
      'source_url': null,
      'processed_at': '2020-11-16T17:12:36+01:00',
      'device_id': null,
      'phone': null,
      'customer_locale': 'de',
      'app_id': 1354745,
      'browser_ip': null,
      'landing_site_ref': null,
      'order_number': 1024,
      'discount_applications': [],
      'discount_codes': [],
      'note_attributes': [],
      'payment_gateway_names': ['manual'],
      'processing_method': 'manual',
      'checkout_id': null,
      'source_name': 'shopify_draft_order',
      'fulfillment_status': 'fulfilled',
      'tax_lines': [
        {
          'price': '17.38',
          'rate': 0.16,
          'title': 'DE MwSt',
          'price_set': {
            'shop_money': {
              'amount': '17.38',
              'currency_code': 'EUR',
            },
            'presentment_money': {
              'amount': '17.38',
              'currency_code': 'EUR',
            },
          },
        },
      ],
      'tags': '',
      'contact_email': 'mowe310@gmail.com',
      'order_status_url':
        'https://toastshopping.myshopify.com/43857412254/orders/7e77c7ab8e219e7a5737b0ea42c31976/authenticate?key=91f6c9308617de66fd2fefc562e24906',
      'presentment_currency': 'EUR',
      'total_line_items_price_set': {
        'shop_money': {
          'amount': '126.00',
          'currency_code': 'EUR',
        },
        'presentment_money': {
          'amount': '126.00',
          'currency_code': 'EUR',
        },
      },
      'total_discounts_set': {
        'shop_money': {
          'amount': '0.00',
          'currency_code': 'EUR',
        },
        'presentment_money': {
          'amount': '0.00',
          'currency_code': 'EUR',
        },
      },
      'total_shipping_price_set': {
        'shop_money': {
          'amount': '0.00',
          'currency_code': 'EUR',
        },
        'presentment_money': {
          'amount': '0.00',
          'currency_code': 'EUR',
        },
      },
      'subtotal_price_set': {
        'shop_money': {
          'amount': '126.00',
          'currency_code': 'EUR',
        },
        'presentment_money': {
          'amount': '126.00',
          'currency_code': 'EUR',
        },
      },
      'total_price_set': {
        'shop_money': {
          'amount': '126.00',
          'currency_code': 'EUR',
        },
        'presentment_money': {
          'amount': '126.00',
          'currency_code': 'EUR',
        },
      },
      'total_tax_set': {
        'shop_money': {
          'amount': '17.38',
          'currency_code': 'EUR',
        },
        'presentment_money': {
          'amount': '17.38',
          'currency_code': 'EUR',
        },
      },
      'line_items': [
        {
          'id': 6206028218526,
          'variant_id': 35654111985822,
          'title': 'Blue Silk Tuxedo',
          'quantity': 1,
          'sku': '',
          'variant_title': 'medium',
          'vendor': 'Liam Fashions',
          'fulfillment_service': 'manual',
          'product_id': 5568753762462,
          'requires_shipping': true,
          'taxable': true,
          'gift_card': false,
          'name': 'Blue Silk Tuxedo - medium',
          'variant_inventory_management': 'shopify',
          'properties': [],
          'product_exists': true,
          'fulfillable_quantity': 0,
          'grams': 268,
          'price': '49.00',
          'total_discount': '0.00',
          'fulfillment_status': 'fulfilled',
          'price_set': {
            'shop_money': {
              'amount': '49.00',
              'currency_code': 'EUR',
            },
            'presentment_money': {
              'amount': '49.00',
              'currency_code': 'EUR',
            },
          },
          'total_discount_set': {
            'shop_money': {
              'amount': '0.00',
              'currency_code': 'EUR',
            },
            'presentment_money': {
              'amount': '0.00',
              'currency_code': 'EUR',
            },
          },
          'discount_allocations': [],
          'duties': [],
          'admin_graphql_api_id': 'gid://shopify/LineItem/6206028218526',
          'tax_lines': [
            {
              'title': 'DE MwSt',
              'price': '6.76',
              'rate': 0.16,
              'price_set': {
                'shop_money': {
                  'amount': '6.76',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '6.76',
                  'currency_code': 'EUR',
                },
              },
            },
          ],
        },
        {
          'id': 6206028251294,
          'variant_id': 35654114214046,
          'title': 'Chequered Red Shirt',
          'quantity': 1,
          'sku': '',
          'variant_title': 'large',
          'vendor': 'Liam Fashions',
          'fulfillment_service': 'manual',
          'product_id': 5568754024606,
          'requires_shipping': true,
          'taxable': true,
          'gift_card': false,
          'name': 'Chequered Red Shirt - large',
          'variant_inventory_management': 'shopify',
          'properties': [],
          'product_exists': true,
          'fulfillable_quantity': 0,
          'grams': 384,
          'price': '31.00',
          'total_discount': '0.00',
          'fulfillment_status': 'fulfilled',
          'price_set': {
            'shop_money': {
              'amount': '31.00',
              'currency_code': 'EUR',
            },
            'presentment_money': {
              'amount': '31.00',
              'currency_code': 'EUR',
            },
          },
          'total_discount_set': {
            'shop_money': {
              'amount': '0.00',
              'currency_code': 'EUR',
            },
            'presentment_money': {
              'amount': '0.00',
              'currency_code': 'EUR',
            },
          },
          'discount_allocations': [],
          'duties': [],
          'admin_graphql_api_id': 'gid://shopify/LineItem/6206028251294',
          'tax_lines': [
            {
              'title': 'DE MwSt',
              'price': '4.28',
              'rate': 0.16,
              'price_set': {
                'shop_money': {
                  'amount': '4.28',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '4.28',
                  'currency_code': 'EUR',
                },
              },
            },
          ],
        },
        {
          'id': 6206028284062,
          'variant_id': 35654121783454,
          'title': 'Classic Leather Jacket',
          'quantity': 1,
          'sku': '',
          'variant_title': 'medium',
          'vendor': 'Liam Fashions',
          'fulfillment_service': 'manual',
          'product_id': 5568754974878,
          'requires_shipping': true,
          'taxable': true,
          'gift_card': false,
          'name': 'Classic Leather Jacket - medium',
          'variant_inventory_management': 'shopify',
          'properties': [],
          'product_exists': true,
          'fulfillable_quantity': 0,
          'grams': 331,
          'price': '46.00',
          'total_discount': '0.00',
          'fulfillment_status': 'fulfilled',
          'price_set': {
            'shop_money': {
              'amount': '46.00',
              'currency_code': 'EUR',
            },
            'presentment_money': {
              'amount': '46.00',
              'currency_code': 'EUR',
            },
          },
          'total_discount_set': {
            'shop_money': {
              'amount': '0.00',
              'currency_code': 'EUR',
            },
            'presentment_money': {
              'amount': '0.00',
              'currency_code': 'EUR',
            },
          },
          'discount_allocations': [],
          'duties': [],
          'admin_graphql_api_id': 'gid://shopify/LineItem/6206028284062',
          'tax_lines': [
            {
              'title': 'DE MwSt',
              'price': '6.34',
              'rate': 0.16,
              'price_set': {
                'shop_money': {
                  'amount': '6.34',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '6.34',
                  'currency_code': 'EUR',
                },
              },
            },
          ],
        },
      ],
      'fulfillments': [
        {
          'id': 2784364265630,
          'order_id': 2892549914782,
          'status': 'success',
          'created_at': '2020-12-11T12:05:41+01:00',
          'service': 'manual',
          'updated_at': '2020-12-11T12:05:41+01:00',
          'tracking_company': null,
          'shipment_status': null,
          'location_id': 50622890142,
          'line_items': [
            {
              'id': 6206028218526,
              'variant_id': 35654111985822,
              'title': 'Blue Silk Tuxedo',
              'quantity': 1,
              'sku': '',
              'variant_title': 'medium',
              'vendor': 'Liam Fashions',
              'fulfillment_service': 'manual',
              'product_id': 5568753762462,
              'requires_shipping': true,
              'taxable': true,
              'gift_card': false,
              'name': 'Blue Silk Tuxedo - medium',
              'variant_inventory_management': 'shopify',
              'properties': [],
              'product_exists': true,
              'fulfillable_quantity': 0,
              'grams': 268,
              'price': '49.00',
              'total_discount': '0.00',
              'fulfillment_status': 'fulfilled',
              'price_set': {
                'shop_money': {
                  'amount': '49.00',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '49.00',
                  'currency_code': 'EUR',
                },
              },
              'total_discount_set': {
                'shop_money': {
                  'amount': '0.00',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '0.00',
                  'currency_code': 'EUR',
                },
              },
              'discount_allocations': [],
              'duties': [],
              'admin_graphql_api_id': 'gid://shopify/LineItem/6206028218526',
              'tax_lines': [
                {
                  'title': 'DE MwSt',
                  'price': '6.76',
                  'rate': 0.16,
                  'price_set': {
                    'shop_money': {
                      'amount': '6.76',
                      'currency_code': 'EUR',
                    },
                    'presentment_money': {
                      'amount': '6.76',
                      'currency_code': 'EUR',
                    },
                  },
                },
              ],
            },
            {
              'id': 6206028251294,
              'variant_id': 35654114214046,
              'title': 'Chequered Red Shirt',
              'quantity': 1,
              'sku': '',
              'variant_title': 'large',
              'vendor': 'Liam Fashions',
              'fulfillment_service': 'manual',
              'product_id': 5568754024606,
              'requires_shipping': true,
              'taxable': true,
              'gift_card': false,
              'name': 'Chequered Red Shirt - large',
              'variant_inventory_management': 'shopify',
              'properties': [],
              'product_exists': true,
              'fulfillable_quantity': 0,
              'grams': 384,
              'price': '31.00',
              'total_discount': '0.00',
              'fulfillment_status': 'fulfilled',
              'price_set': {
                'shop_money': {
                  'amount': '31.00',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '31.00',
                  'currency_code': 'EUR',
                },
              },
              'total_discount_set': {
                'shop_money': {
                  'amount': '0.00',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '0.00',
                  'currency_code': 'EUR',
                },
              },
              'discount_allocations': [],
              'duties': [],
              'admin_graphql_api_id': 'gid://shopify/LineItem/6206028251294',
              'tax_lines': [
                {
                  'title': 'DE MwSt',
                  'price': '4.28',
                  'rate': 0.16,
                  'price_set': {
                    'shop_money': {
                      'amount': '4.28',
                      'currency_code': 'EUR',
                    },
                    'presentment_money': {
                      'amount': '4.28',
                      'currency_code': 'EUR',
                    },
                  },
                },
              ],
            },
            {
              'id': 6206028284062,
              'variant_id': 35654121783454,
              'title': 'Classic Leather Jacket',
              'quantity': 1,
              'sku': '',
              'variant_title': 'medium',
              'vendor': 'Liam Fashions',
              'fulfillment_service': 'manual',
              'product_id': 5568754974878,
              'requires_shipping': true,
              'taxable': true,
              'gift_card': false,
              'name': 'Classic Leather Jacket - medium',
              'variant_inventory_management': 'shopify',
              'properties': [],
              'product_exists': true,
              'fulfillable_quantity': 0,
              'grams': 331,
              'price': '46.00',
              'total_discount': '0.00',
              'fulfillment_status': 'fulfilled',
              'price_set': {
                'shop_money': {
                  'amount': '46.00',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '46.00',
                  'currency_code': 'EUR',
                },
              },
              'total_discount_set': {
                'shop_money': {
                  'amount': '0.00',
                  'currency_code': 'EUR',
                },
                'presentment_money': {
                  'amount': '0.00',
                  'currency_code': 'EUR',
                },
              },
              'discount_allocations': [],
              'duties': [],
              'admin_graphql_api_id': 'gid://shopify/LineItem/6206028284062',
              'tax_lines': [
                {
                  'title': 'DE MwSt',
                  'price': '6.34',
                  'rate': 0.16,
                  'price_set': {
                    'shop_money': {
                      'amount': '6.34',
                      'currency_code': 'EUR',
                    },
                    'presentment_money': {
                      'amount': '6.34',
                      'currency_code': 'EUR',
                    },
                  },
                },
              ],
            },
          ],
          'tracking_number': null,
          'tracking_numbers': [],
          'tracking_url': null,
          'tracking_urls': [],
          'receipt': {},
          'name': '#1024.1',
          'admin_graphql_api_id': 'gid://shopify/Fulfillment/2784364265630',
        },
      ],
      'refunds': [],
      'total_tip_received': '0.0',
      'original_total_duties_set': null,
      'current_total_duties_set': null,
      'admin_graphql_api_id': 'gid://shopify/Order/2892549914782',
      'shipping_lines': [],
      'billing_address': {
        'first_name': 'Moritz',
        'address1': 'Am Steinbecker Feld 13',
        'phone': '017623949221',
        'city': 'Buchholz',
        'zip': '21244',
        'province': 'Niedersachen',
        'country': 'Germany',
        'last_name': 'Weber',
        'address2': null,
        'company': null,
        'latitude': 53.32412,
        'longitude': 9.8498,
        'name': 'Moritz Weber',
        'country_code': 'DE',
        'province_code': null,
      },
      'shipping_address': {
        'first_name': 'Moritz',
        'address1': 'Am Steinbecker Feld 13',
        'phone': '017623949221',
        'city': 'Buchholz',
        'zip': '21244',
        'province': 'Niedersachen',
        'country': 'Germany',
        'last_name': 'Weber',
        'address2': null,
        'company': null,
        'latitude': 53.32412,
        'longitude': 9.8498,
        'name': 'Moritz Weber',
        'country_code': 'DE',
        'province_code': null,
      },
      'customer': {
        'id': 4016387850398,
        'email': 'mowe310@gmail.com',
        'accepts_marketing': false,
        'created_at': '2020-09-10T16:13:39+02:00',
        'updated_at': '2020-11-16T17:12:37+01:00',
        'first_name': 'Moritz',
        'last_name': 'Weber',
        'orders_count': 10,
        'state': 'disabled',
        'total_spent': '1260.00',
        'last_order_id': 2892549914782,
        'note': null,
        'verified_email': true,
        'multipass_identifier': null,
        'tax_exempt': false,
        'phone': null,
        'tags': '',
        'last_order_name': '#1024',
        'currency': 'EUR',
        'accepts_marketing_updated_at': '2020-09-10T16:13:39+02:00',
        'marketing_opt_in_level': null,
        'admin_graphql_api_id': 'gid://shopify/Customer/4016387850398',
        'default_address': {
          'id': 4677999591582,
          'customer_id': 4016387850398,
          'first_name': 'Moritz',
          'last_name': 'Weber',
          'company': '',
          'address1': 'Am Steinbecker Feld 13',
          'address2': '',
          'city': 'Buchholz',
          'province': 'Niedersachen',
          'country': 'Germany',
          'zip': '21244',
          'phone': '017623949221',
          'name': 'Moritz Weber',
          'province_code': null,
          'country_code': 'DE',
          'country_name': 'Germany',
          'default': true,
        },
      },
    },
  },
};
